### ISSUE TITLE
 Sketch a plan for scaling single file operations to databases or large data repositories

### ISSUE THREAD

**Issue by AdkPete** [srodney/diffimageml#21]

**Comment by srodney** [comment]
This feels a little insufficient, but for the moment here's a sketch: 

![data_transfer_plan](https://user-images.githubusercontent.com/1355473/105500564-0c38e280-5c91-11eb-8c3d-2c9528518ce6.png)

What we're missing here is any real thinking about a database to track the planting of fakes over multiple epochs, but that seems to be a largely separate issue from dealing with a remote data repository.

**Comment by srodney** [comment]
This is the sketch for how we could operate on a collection of images in a time series, using simulated SN so that the brightness of a source evolves over time.   This whole flowchart fits inside the "Fake Planting" box inside the yellow box in the data-transfer plan above.   Building this functionality is NOT a target for the current Sprint2, but is part of the larger product plan.

![fakeSN_catalog_plan](https://user-images.githubusercontent.com/1355473/105513562-786f1280-5ca0-11eb-8721-2a8e60564feb.png)
